services:
  airflow:
    image: apache/airflow:3.1.1-python3.12
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "true"
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - ./fastapi_app/ai_model:/opt/airflow/ai_model
    ports:
      - "${AIRFLOW_PORT}:8080"
    command: airflow standalone

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    volumes:
      - ./fastapi_app/ai_model:/app/ai_model