services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "true"
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - ./ml_core:/opt/airflow/ml_core
    ports:
      - "${AIRFLOW_PORT}:8080"
    command: airflow standalone
    depends_on:
      - hadoop

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    volumes:
      - ./ml_core:/ml_core
    depends_on:
      - hadoop

  hadoop:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: hadoop
    ports:
      - "${HDFS_WEB_PORT}:50070"
      - "${HDFS_PORT}:9000"
      - "${HDFS_NODE_MANAGER_PORT}:8042"
    environment:
      - HADOOP_HEAPSIZE=512
      - FORMAT_NAMENODE=false
    volumes:
      - hadoop_data:/tmp/hadoop-root/dfs/

volumes:
  hadoop_data: