FROM apache/airflow:3.1.1-python3.12

USER root
RUN apt-get update && apt-get install -y gcc g++
USER airflow

COPY requirements_airflow.txt .
RUN pip install --no-cache-dir -r requirements_airflow.txt

COPY ml_core/ ./ml_core/
COPY storage/ ./storage/

ENV PYTHONPATH=/opt/airflow:$PYTHONPATH